accounts/urls.py
from django.urls import path
from accounts import views

from django.contrib.auth.views import LogoutView

app_name = "accounts"

urlpatterns = [
    path('login/',views.CustomLoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(next_page="/"),name='logout'),
    path('register/',views.RegisterView.as_view(),name='register')

]

core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',include("todo.urls"),name="index")
    

]

todo/urls.py
from django.urls import path
from .views import *

urlpatterns = [

    path('tasks/',TasksList.as_view(),name="tasks_list"),
    path('tasks/create',CreateTask.as_view(),name="tasks_create"),
    path('tasks/edit/<int:pk>',UpdateTask.as_view(),name="tasks_edit"),
    path('tasks/delete/<int:pk>',DeleteTask.as_view(),name="tasks_delete"),
    path('tasks/done/<int:pk>',DoneTask.as_view(),name="tasks_done"),
    
   
]

accounts/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

User = get_user_model()


class Task(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    content = models.TextField()
    is_done = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        order_with_respect_to = 'user'

    def __str__(self):
        return f"{self.id} - {self.user}"

accounts/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.shortcuts import redirect

# Create your views here.

class CustomLoginView(LoginView):
    
    template_name = "accounts/login.html"
    next_page = reverse_lazy("tasks_list")
    fields = ['username','password']

class RegisterView(FormView):
    form_class = UserCreationForm
    success_url = reverse_lazy("tasks_list")
    template_name = "accounts/register.html"

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request,user)
        return super().form_valid(form)
    
    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            redirect(reverse_lazy("tasks_list"))
        return super().get(request, *args, **kwargs)

todo/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import ListView,CreateView,UpdateView,DeleteView,View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Task
from django.urls import reverse_lazy

# Create your views here.


class TasksList(ListView,LoginRequiredMixin):
    template_name = 'todo/tasks/tasks_list.html'
    context_object_name = 'tasks'
    
    def get_queryset(self):
        tasks = Task.objects.filter(user = self.request.user)

        return tasks 
    
class CreateTask(CreateView,LoginRequiredMixin):
    model = Task
    fields = ['content']
    success_url = reverse_lazy("tasks_list")
    

    def form_valid(self,form):
        form.instance.user = self.request.user
        return super(CreateTask,self).form_valid(form)
    


class UpdateTask(UpdateView,LoginRequiredMixin):
    model = Task
    fields = ['content']
    success_url = reverse_lazy("tasks_list")
    template_name = 'todo/tasks/tasks_edit.html'

class DeleteTask(DeleteView,LoginRequiredMixin):
    model = Task
    success_url = reverse_lazy("tasks_list")
    template_name = 'todo/tasks/tasks_delete.html'

class DoneTask(View,LoginRequiredMixin):

    def get(self,*args,**kwargs):
        pk = kwargs.get("pk")
        task = get_object_or_404(Task,user=self.request.user,id=pk)
        if not task.is_done:
            task.is_done = True
        elif task.is_done:
            task.is_done = False
        task.save()
        return redirect(reverse_lazy("tasks_list"))
        
    
    

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block extra_css %}
<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
</style>
<link href="https://getbootstrap.com/docs/5.1/examples/sign-in/signin.css" rel="stylesheet">
{% endblock %}


{% block content %}
<main class="form-signin text-center">
    <form action="{% url 'accounts:login' %}" method="POST">
           
        <h1 class="h3 mb-3 fw-normal">Please Sign In</h1>
        {% csrf_token %}
        <div class="form-floating">
            <input type="username" name="username" class="form-control" id="floatingInput"
                placeholder="name@example.com">
            <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating">
            <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Password</label>
        </div>

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Sign In</button>
        <p class="mt-3 mb-2">Dont have an account then <a href="{% url 'accounts:register' %}">create one</a></p>
    </form>
    {% if form.errors %}
    <div class="alert alert-error">
        <h6>Please fix the following errors</h6>
        <ul>
            {% for field in form %}
            {% if field.errors %}
            {% for error in field.errors %}
            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
            {% endif %}
            {% endfor %}
        </ul>
        {% if form.non_field_errors %}
        {{ form.non_field_errors }}
        {% endif %}
    </div>
    {% endif %}
</main>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}

{% block title %} Register {% endblock %}

{% block extra_css %}
<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
</style>
<link href="https://getbootstrap.com/docs/5.1/examples/sign-in/signin.css" rel="stylesheet">
{% endblock %}


{% block content %}
<main class="form-signin text-center">
    <form action="{% url 'accounts:register' %}" method="POST">
            
        <h1 class="h3 mb-3 fw-normal">Please Register</h1>
        {% csrf_token %}
        <div class="form-floating">
            <input type="username" name="username" class="form-control" id="floatingInput"
                placeholder="name@example.com">
            <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating">
            <input type="password" name="password1" class="form-control mb-0" id="floatingPassword"
                placeholder="Password">
            <label for="floatingPassword">Password</label>
        </div>
        <div class="form-floating">
            <input type="password" name="password2" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Repeate Password</label>
        </div>


        <button class="w-100 btn btn-lg btn-primary" type="submit">Register</button>
        <p class="mt-3 mb-2">Already have an account then <a href="{% url 'accounts:login' %}"> login</a></p>
        <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
    </form>
    {% if form.errors %}
    <div class="alert alert-error">
        <h6>Please fix the following errors</h6>
        <ul>
            {% for field in form %}
            {% if field.errors %}
            {% for error in field.errors %}
            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
            {% endif %}
            {% endfor %}
        </ul>
        {% if form.non_field_errors %}
        {{ form.non_field_errors }}
        {% endif %}
    </div>
    {% endif %}
</main>


{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="generator" content="Hugo 0.88.1">
    <title>{% block title %} {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <style>
        body {
            width: 100%;
            height: 100vh;            
            background: linear-gradient(to bottom, #e6e6e6 0%, #ffffff 100%);
        }
    </style>
    {% block extra_css %}{% endblock %}
</head>

<body>
    {% block content %}{% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>
    {% block extra_js %}{% endblock %}
</body>

</html>

templates/todo/tasks/tasks_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Edit Task {% endblock %}
{% block extra_css %}
{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
	<div class="modal-dialog" role="document">
		<div class="modal-content rounded-5 shadow">
			

			<div class="modal-body p-5 pt-0">

				<form method="POST" action="">
					{% csrf_token %}
					<div class="form-floating mb-3">
                        
						<h2 > want to delete this Task?</h2>
					</div>
					<button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Confirm</button>
				</form>				
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block extra_js %}{% endblock %}

templates/todo/tasks/tasks_edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Edit Task {% endblock %}
{% block extra_css %}
{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
	<div class="modal-dialog" role="document">
		<div class="modal-content rounded-5 shadow">
			<div class="modal-header p-5 pb-4 border-bottom-0">
				<!-- <h5 class="modal-title">Modal title</h5> -->
				<h2 class="fw-bold mb-0">Edit Form</h2>
				<a type="button" class="btn-close" href="{% url 'tasks_list' %}"></a>
			</div>

			<div class="modal-body p-5 pt-0">

				<form method="POST" action="">
					{% csrf_token %}
					<div class="form-floating mb-3">
                        
						<input name="content" class="form-control rounded-4" 
							placeholder="enter the title" value="{{ form.title.value }}">
						<label for="floatingInput">Title</label>
					</div>
					<button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Change</button>
				</form>				
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block extra_js %}{% endblock %}

templates/todo/tasks/tasks_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Todo List {% endblock %}
{% block extra_css %}{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-5 shadow">
      <div class="modal-header p-5 pb-4 border-bottom-0">
        <!-- <h5 class="modal-title">Modal title</h5> -->
        <h2 class="fw-bold mb-0">Todo App</h2>
        <a type="button" class="btn-close" href=""></a>
      </div>

      <div class="modal-body p-5 pt-0">

        <form class="pt-3" method="post" action="{% url 'tasks_create' %}">
          {% csrf_token %}
          <div class="input-group mb-3">
            <input type="text" class="form-control rounded-4" name="content" placeholder="Enter task title"
              aria-label="Recipient's username" aria-describedby="button-addon2">
            <button class="btn btn-primary" type="submit">Add</button>
          </div>


          <hr class="my-4">
          {% for task in tasks %}
          <div class="input-group py-1">
            <span type="text" class="form-control" aria-label="Text input with segmented dropdown button">
              {% if task.is_done == True %}
              <strike>{{task.content}}</strike>
              {% else %}
              <span>{{task.content}}</span>
              {% endif %}
            </span>
            
         
              <a type="submit" class="btn btn-danger" href="{% url 'tasks_delete' pk=task.id   %}" ><i class="bi bi-trash"></i></a>
           
            
            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"
              aria-expanded="false">
              <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
              {% if not task.is_done %}
              <li><a class="dropdown-item" href="{% url 'tasks_done' pk=task.id  %}">Done</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'tasks_done' pk=task.id  %}">UnDone</a></li>
              {% endif%}
              <li><a class="dropdown-item" href="{% url 'tasks_edit' pk=task.id %}">Edit</a></li>
            </ul>
          </div>
      
          {% endfor %}          
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}{% endblock %}